-- Adds new-member and guest Q&A knowledge for ask.dt.
-- Run this in the Supabase SQL editor for production/staging projects.

insert into public.church_info (id, topic, question, answer, source_url, last_updated)
values
  ('info-service-times', 'Service Times', 'What are the church service times?', 'Sunday School is at 8:30 AM, Morning Worship is at 9:30 AM, and Bible Study is at 11:00 AM and 6:00 PM.', null, '2026-06-17'),
  ('info-sunday-school', 'Service Times', 'What time is Sunday School?', 'Sunday School is at 8:30 AM, Morning Worship is at 9:30 AM, and Bible Study is at 11:00 AM and 6:00 PM.', null, '2026-06-17'),
  ('info-location', 'Plan a Visit', 'Where is David''s Temple located?', 'David''s Temple Missionary Baptist Church is located at 11273 Stewart Road, Tanner, AL 35671.', null, '2026-06-17'),
  ('info-guest-arrival', 'Plan a Visit', 'What should I do when I arrive?', 'When you arrive, greeters, ushers, and parking attendants will be ready to help you find your way. If this is your first time visiting, let a parking attendant, greeter, or usher know and they will gladly help you from the parking lot to the sanctuary.', null, '2026-06-17'),
  ('info-parking', 'Plan a Visit', 'Where do I park?', 'Parking attendants will help direct you to an available space. David''s Temple is currently working to expand parking, so guests are encouraged to arrive a few minutes early.', null, '2026-06-17'),
  ('info-worship-expectations', 'Plan a Visit', 'What is worship like?', 'Worship includes prayer, singing, Scripture, giving, and preaching from God''s Word. You can expect a warm church family, heartfelt worship, and a message that helps you understand and apply the Bible to your life.', null, '2026-06-17'),
  ('info-guest-seating', 'Plan a Visit', 'Where do I sit?', 'You are welcome to sit anywhere in the sanctuary. There are no assigned seats. If the sanctuary is full or you need help finding a comfortable place to sit, one of the ushers will gladly assist you.', null, '2026-06-17'),
  ('info-kids', 'Children', 'What about my kids?', 'David''s Temple offers nursery and youth church ministry for children from 0-14 years old. These ministries provide a safe, caring, and age-appropriate space where children can learn about Jesus and be encouraged in their faith.', null, '2026-06-17'),
  ('info-dress-code', 'Plan a Visit', 'Is there a church dress code?', 'Come as you are. At David''s Temple, you will see a little bit of everything. Some people dress up, and others dress more casually. We care far more about your presence than your outfit. We simply want you to feel welcome as you worship with us.', null, '2026-06-17'),
  ('info-first-time-singled-out', 'Plan a Visit', 'Will I be singled out if I come as a first-time visitor?', 'No. We want to welcome you, but we will not embarrass you. You may be greeted warmly by our members, but we do not want you to feel pressured or put on the spot. We are simply grateful that you chose to worship with us.', null, '2026-06-17'),
  ('info-serving', 'Serving', 'How can I serve?', 'A good next step is to visit the Join A Ministry page and connect with the ministry leader for the area where you would like to serve.', '/serve', '2026-06-17'),
  ('info-serving-before-membership', 'Serving', 'Can I serve before officially joining the church?', 'There are volunteer opportunities where non-members can partner with David''s Temple in serving the community. When those opportunities are available, they will be made public. Membership is required before officially joining a ministry within the church, with the exception of the children''s choir. All children are welcome to sing praises to the Lord.', null, '2026-06-17'),
  ('info-new-member-orientation', 'New Members', 'Is there an orientation or training process?', 'When a believer becomes a member at David''s Temple, they are partnered with a current member and invited to follow a new-member orientation process centered on connecting new members to ministries and establishing deep relationships.', null, '2026-06-17'),
  ('info-children-serving', 'Serving', 'Can children serve?', 'Children are invited to serve as Junior Ushers, in the Youth Choir, and for special programs throughout the year. The level of service depends on the maturity of the individual child, but David''s Temple encourages children to get engaged in serving as early as possible.', null, '2026-06-17'),
  ('info-background-checks', 'Serving', 'Are background checks required for any ministries?', 'Yes. One of the values of the children''s ministry is safety, so background checks are required for anyone working with the youth.', null, '2026-06-17'),
  ('info-serving-uniforms', 'Serving', 'What should I wear when serving?', 'Uniforms and dress are at the discretion of each ministry. Ministry leaders are encouraged to exercise sensitivity when creating uniform expectations so members are not discouraged from serving.', null, '2026-06-17'),
  ('info-one-time-serving', 'Serving', 'Are there virtual or one-time serving opportunities?', 'Yes. Members can serve as part of a lead team, which is an opportunity to serve without a long-term commitment. Because we live in a digital ecosystem, David''s Temple also needs people who want to use their gifts behind the scenes on digital lead teams.', null, '2026-06-17'),
  ('info-professional-skills', 'Serving', 'Can professional career skills be used to serve?', 'Yes. David''s Temple is undergoing a digital transformation and has significant need for expertise in areas like IT, marketing, and legal. People with those backgrounds who want to use their gifts to the glory of God are encouraged to connect with a ministry leader or send a message to the church expressing their desire to serve.', null, '2026-06-17'),
  ('info-childcare-serving', 'Serving', 'Is childcare provided while serving?', 'Childcare is provided during worship. During service opportunities, childcare options are determined by the availability of volunteers to support the event.', null, '2026-06-17'),
  ('info-leadership-development', 'Leadership', 'Are there leadership development opportunities?', 'David''s Temple''s mission is to evangelize, equip, and empower believers to serve to the glory of God. Because of that core belief, the church holds a monthly leadership meeting that is not restricted to ministry leaders, but is open to all members who desire to grow and be empowered to lead and serve.', null, '2026-06-17'),
  ('info-spiritual-leader-training', 'Leadership', 'Are team leaders trained spiritually as well as operationally?', 'David''s Temple desires to continuously develop leaders at every level. From Sunday School, to Bible Study, and even the Sunday sermon, there is an intentional approach to growing all members spiritually. The church strives to emphasize Christian Education as the cornerstone for spiritual development.', null, '2026-06-17'),
  ('info-care', 'Care', 'How do I submit a prayer or care request?', 'Prayer requests can be submitted through the Submit a Prayer Request card on the Resources page. The form allows you to include your name and contact information for follow-up or submit the request anonymously.', '/resources', '2026-06-17'),
  ('info-pastor-background', 'Pastor', 'What is the pastor''s background?', 'Information about Pastor Keith can be found on the Pastor Bio page, including his background, education, ministry heart, and connection to the Tanner community.', '/pastor', '2026-06-17'),
  ('info-age-groups', 'Ministries', 'Are there specific groups for young adults, seniors, parents, or other stages of life?', 'David''s Temple strives to offer ministry in an age-group-specific format to meet the needs of believers based on their unique stage in life. Educational ministries are offered for elementary children, teens, young adults, middle school, and senior adults.', null, '2026-06-17'),
  ('info-financial-transparency', 'Church Life', 'Is the church financially transparent?', 'Yes. David''s Temple believes in transparency and accountability at every level. The church holds an annual business meeting at the beginning of each calendar year where members receive a booklet with the previous year''s complete expense report, the new year''s budget, and the church''s initiatives for the year.', null, '2026-06-17'),
  ('info-pastor-office-hours', 'Pastor', 'Does the pastor have office hours?', 'Pastor Keith''s schedule is relatively flexible because he is bi-vocational. Meetings can be scheduled virtually or in person by submitting a message on the Pastor Bio page.', '/pastor', '2026-06-17'),
  ('info-counseling', 'Care', 'Is counseling available?', 'Counseling sessions, including needs such as grief, divorce, or marital support, can be scheduled with Pastor Keith by submitting a message through the Pastor Bio page.', '/pastor', '2026-06-17')
on conflict (id) do update set
  topic = excluded.topic,
  question = excluded.question,
  answer = excluded.answer,
  source_url = excluded.source_url,
  last_updated = excluded.last_updated,
  updated_at = now();
